---
apiVersion: v1
kind: ConfigMap
metadata:
  name: settings-configmap
data:
  DATABASE_HOST: alfa-30
  DATABASE_PORT: "1521"
  DATABASE_USER: MTRX
  DATABASE_PASSWORD: "12345"
  DATABASE_SERVICE_NAME: cdb1
  DATABASE_POOL_SIZE: "10"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: settings-deployment
  labels:
    app: settings
spec:
  replicas: 3
  selector:
    matchLabels:
      app: settings
  template:
    metadata:
      labels:
        app: settings
    spec:
      containers:
      - name: settings-app
        image: "artifactory.cinimex.ru/alfmatrix_docker/settings:0.1"
        ports:
        - containerPort: 8000
        env:
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: settings-configmap
                key: DATABASE_HOST
          - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: settings-configmap
                  key: DATABASE_PORT
          - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: settings-configmap
                  key: DATABASE_USER
          - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: settings-configmap
                  key: DATABASE_PASSWORD
          - name: DATABASE_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: settings-configmap
                  key: DATABASE_SERVICE_NAME
          - name: DATABASE_POOL_SIZE
              valueFrom:
                configMapKeyRef:
                  name: settings-configmap
                  key: DATABASE_POOL_SIZE