---
apiVersion: v1
kind: ConfigMap
metadata:
  name: template-configmap
data:
  DATABASE_HOST=ХОСТ_БД
  DATABASE_PORT=ПОРТ_БД
  DATABASE_USER=ПОЛЬЗОВАТЕЛЬ_БД
  DATABASE_PASSWORD=ПАРОЛЬ_БД
  DATABASE_SERVICE_NAME=СЕРВИС_БД
  DATABASE_POOL_SIZE=РАЗМЕР_ПУЛА_КОННЕКТОВ
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-deployment
  labels:
    app: template
spec:
  replicas: 3
  selector:
    matchLabels:
      app: template
  template:
    metadata:
      labels:
        app: template
    spec:
      containers:
      - name: template-app
        image: {ваш_логин_на_докерхаб}/template:1
        ports:
        - containerPort: 8000
        env:
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: template-configmap
                key: DATABASE_HOST
          - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: template-configmap
                  key: DATABASE_PORT
          - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: template-configmap
                  key: DATABASE_USER
          - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: template-configmap
                  key: DATABASE_PASSWORD
          - name: DATABASE_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: template-configmap
                  key: DATABASE_SERVICE_NAME
          - name: DATABASE_POOL_SIZE
              valueFrom:
                configMapKeyRef:
                  name: template-configmap
                  key: DATABASE_POOL_SIZE